using System;using System.Linq;using UnityEngine;using UnityEngine.AI;using UnityEditor;using UnityEditor.SceneManagement;using UnityEngine.SceneManagement;using Unity.AI.Navigation;using Object=UnityEngine.Object;
public static class BuildPrototypeShelter {
 const string Root="Assets/04_Assets/PrototypeShelterV1";static Transform art;
 static Material Mat(string n)=>AssetDatabase.LoadAssetAtPath<Material>(Root+"/Materials/"+n+".mat");
 static GameObject Model(string n,Vector3 p,float yaw=0,Transform parent=null){var go=(GameObject)PrefabUtility.InstantiatePrefab(AssetDatabase.LoadAssetAtPath<GameObject>(Root+"/Prefabs/"+n+".prefab"));go.transform.SetParent(parent!=null?parent:art,false);go.transform.localPosition=p;go.transform.localRotation=Quaternion.Euler(0,yaw,0);return go;}
 static GameObject Block(string name,Vector3 pos,Vector3 scale,string mat,bool collide=false,Transform parent=null){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);go.name=name;go.transform.SetParent(parent!=null?parent:art,false);go.transform.localPosition=pos;go.transform.localScale=scale;go.GetComponent<Renderer>().sharedMaterial=Mat(mat);if(!collide){Object.DestroyImmediate(go.GetComponent<Collider>());go.layer=2;}else go.layer=LayerMask.NameToLayer("EnvironmentWall");return go;}
 static void Collider(GameObject go,Vector3 center,Vector3 size,int layer){var box=go.GetComponent<BoxCollider>();if(box==null)box=go.AddComponent<BoxCollider>();box.center=center;box.size=size;go.layer=layer;}
 static void Label(string body,Vector3 pos,float yaw,float size=.25f,Transform parent=null){var go=new GameObject("Label "+body);go.transform.SetParent(parent!=null?parent:art,false);go.transform.localPosition=pos;go.transform.localRotation=Quaternion.Euler(0,yaw,0);var text=go.AddComponent<TextMesh>();text.text=body;text.anchor=TextAnchor.MiddleCenter;text.alignment=TextAlignment.Center;text.characterSize=size;text.fontSize=64;text.color=new Color(.89f,.84f,.65f);go.layer=2;}
 static void AttachVisual(GameObject root,string name,Vector3 pos,Vector3 colliderSize){var renderer=root.GetComponent<MeshRenderer>();if(renderer!=null)renderer.enabled=false;root.transform.SetPositionAndRotation(pos,Quaternion.identity);root.transform.localScale=Vector3.one;var child=Model(name,Vector3.zero,0,root.transform);child.name="PrototypeVisual";Collider(root,new Vector3(0,colliderSize.y/2,0),colliderSize,root.layer);var obstacle=root.GetComponent<NavMeshObstacle>();if(obstacle!=null){obstacle.center=new Vector3(0,colliderSize.y/2,0);obstacle.size=colliderSize;}}
 static void PlayerVisual(){var p=Object.FindFirstObjectByType<PlayerController>();if(p==null)return;if(p.transform.Find("PrototypeVisual")!=null)throw new Exception("Player already has prototype visual");var body=p.GetComponent<MeshRenderer>();if(body!=null)body.enabled=false;foreach(var w in p.GetComponentsInChildren<Weapon>(true)){var r=w.GetComponent<MeshRenderer>();if(r!=null)r.enabled=false;}var visual=Model("Survivor",new Vector3(0,-.5f,0),0,p.transform);visual.name="PrototypeVisual";p.visualAnimator=visual.GetComponent<Animator>();var cc=p.GetComponent<CharacterController>();cc.height=1.8f;cc.radius=.32f;cc.center=new Vector3(0,.4f,0);var box=p.GetComponent<BoxCollider>();if(box!=null){box.center=new Vector3(0,.4f,0);box.size=new Vector3(.6f,1.8f,.6f);}foreach(var t in visual.GetComponentsInChildren<Transform>(true))t.gameObject.layer=LayerMask.NameToLayer("Player");EditorUtility.SetDirty(p);}
 public static object Main(){if(EditorApplication.isPlaying)throw new Exception("Stop Play");if(SceneManager.GetActiveScene().name!="01_Main")throw new Exception("Main required");if(GameObject.Find("PrototypeShelter_V1")!=null)throw new Exception("Already applied");
  art=new GameObject("PrototypeShelter_V1").transform;var oldWall=SceneManager.GetActiveScene().GetRootGameObjects().Single(x=>x.name=="wall");oldWall.SetActive(false);
  var ground=GameObject.Find("Ground");ground.GetComponent<Renderer>().sharedMaterial=Mat("Outside");
  var plaza=GameObject.CreatePrimitive(PrimitiveType.Plane);plaza.name="Courtyard 48m";plaza.transform.SetParent(art,false);plaza.transform.position=new Vector3(0,-.49f,0);plaza.transform.localScale=new Vector3(4.8f,1,4.8f);plaza.GetComponent<Renderer>().sharedMaterial=Mat("Courtyard");Object.DestroyImmediate(plaza.GetComponent<Collider>());plaza.layer=2;
  Block("North south service lane",new Vector3(0,-.48f,0),new Vector3(7,.018f,72),"Walkway");Block("East west service lane",new Vector3(0,-.479f,0),new Vector3(72,.018f,7),"Walkway");
  for(int side=0;side<4;side++){var q=Quaternion.Euler(0,side*90,0);foreach(int x in new[]{-22,-18,-14,-10,-6,6,10,14,18,22}){var go=Model("PerimeterWall",q*new Vector3(x,-.5f,24),side*90);Collider(go,new Vector3(0,1.28f,0),new Vector3(4.15f,2.56f,.65f),LayerMask.NameToLayer("EnvironmentWall"));}foreach(int x in new[]{-4,4})Block("Gate pier",q*new Vector3(x,1.05f,24),new Vector3(.45f,3.1f,.45f),"Steel",true);var lintel=Block("Gate header",q*new Vector3(0,2.72f,24),new Vector3(8.5f,.3f,.4f),"Olive");lintel.transform.rotation=q;Label("SHELTER 01 / "+new[]{"NORTH","EAST","SOUTH","WEST"}[side],q*new Vector3(0,2.72f,24.23f),side*90,.2f);for(int k=0;k<6;k++){var p=q*new Vector3(-2.5f+k,-.464f,22);var strip=Block("Gate threshold marking",p,new Vector3(.36f,.015f,2),"Safety");strip.transform.rotation=q;}}
  var core=Object.FindFirstObjectByType<Core>();AttachVisual(core.gameObject,"CoreGenerator",new Vector3(0,-.5f,0),new Vector3(3,2.65f,2.3f));
  var residence=Object.FindFirstObjectByType<ResidenceBuilding>();AttachVisual(residence.gameObject,"ResidenceModule",new Vector3(-15,-.5f,-15),new Vector3(8,3.2f,5));
  var lab=Object.FindFirstObjectByType<ResearchLab>();AttachVisual(lab.gameObject,"ResearchCabin",new Vector3(-15,-.5f,15),new Vector3(6,3.2f,4));lab.transform.rotation=Quaternion.Euler(0,180,0);
  var workshop=Model("WorkshopModule",new Vector3(15,-.5f,15),180);Collider(workshop,new Vector3(0,1.6f,0),new Vector3(7,3.2f,4.5f),LayerMask.NameToLayer("EnvironmentWall"));
  for(int i=0;i<4;i++){var crate=Model("SupplyCrate",new Vector3(10.8f+(i%2)*1.3f,-.5f+(i/2)*.9f,13));Collider(crate,new Vector3(0,.45f,0),new Vector3(1.16f,.9f,.85f),LayerMask.NameToLayer("EnvironmentWall"));}
  foreach(var p in new[]{new Vector3(-12,0,-9),new Vector3(12,0,9),new Vector3(10,0,-16)}){var b=Model("Barricade",p+Vector3.down*.5f);Collider(b,new Vector3(0,.5f,0),new Vector3(3,1,.95f),LayerMask.NameToLayer("EnvironmentWall"));}
  foreach(var p in new[]{new Vector3(-21,0,-20),new Vector3(21,0,-20),new Vector3(-21,0,20),new Vector3(21,0,20),new Vector3(-8,0,8),new Vector3(8,0,-8)}){var mast=Model("LightMast",p+Vector3.down*.5f);Collider(mast,new Vector3(0,2.4f,0),new Vector3(.2f,4.8f,.2f),LayerMask.NameToLayer("EnvironmentWall"));var lamp=new GameObject("Warm work light");lamp.transform.SetParent(mast.transform,false);lamp.transform.localPosition=new Vector3(0,4.3f,.65f);var light=lamp.AddComponent<Light>();light.type=LightType.Point;light.color=new Color(1,.8f,.56f);light.intensity=2.3f;light.range=12;light.shadows=LightShadows.None;}
  // Flat ground markings communicate room for future player construction.
  foreach(var center in new[]{new Vector3(-11,0,0),new Vector3(11,0,0)}){for(int i=-1;i<=1;i++)for(int j=-1;j<=1;j++){var c=center+new Vector3(i*3,-.455f,j*3);Block("Build bay corner X",c+new Vector3(-1,0,-1),new Vector3(.65f,.01f,.07f),"Safety");Block("Build bay corner Z",c+new Vector3(-1.3f,0,-.7f),new Vector3(.07f,.01f,.65f),"Safety");}}
  var portal=Object.FindFirstObjectByType<ScenePortal>();portal.transform.position=new Vector3(18,-.5f,-18);portal.GetComponent<Renderer>().enabled=false;Collider(portal.gameObject,new Vector3(0,1,0),new Vector3(1.3f,2,.65f),portal.gameObject.layer);Block("Exit terminal",new Vector3(0,1,0),new Vector3(1.3f,2,.6f),"Olive",false,portal.transform);Block("Exit display",new Vector3(0,1.3f,.32f),new Vector3(.95f,.65f,.04f),"Glow",false,portal.transform);Label("COLLECTION\n[E]",new Vector3(0,1.3f,.35f),0,.12f,portal.transform);
  foreach(var maker in Object.FindObjectsByType<EnemyMaker>(FindObjectsSortMode.None)){var p=maker.transform.position;if(Mathf.Abs(p.x)>Mathf.Abs(p.z))maker.transform.position=new Vector3(Mathf.Sign(p.x)*34,0,0);else maker.transform.position=new Vector3(0,0,Mathf.Sign(p.z)*34);}
  var spawn=Object.FindFirstObjectByType<SceneSpawnPoint>();spawn.transform.SetPositionAndRotation(new Vector3(4,0,-7),Quaternion.identity);Object.FindFirstObjectByType<PlayerController>().transform.position=spawn.transform.position;PlayerVisual();
  var sun=Object.FindObjectsByType<Light>(FindObjectsSortMode.None).FirstOrDefault(l=>l.type==LightType.Directional);if(sun!=null){sun.transform.rotation=Quaternion.Euler(48,-35,0);sun.intensity=1.05f;sun.color=Object.FindFirstObjectByType<GameManager>().dayLightColor;sun.shadows=LightShadows.Soft;}
  RenderSettings.ambientMode=UnityEngine.Rendering.AmbientMode.Trilight;RenderSettings.ambientSkyColor=new Color(.49f,.56f,.64f);RenderSettings.ambientEquatorColor=new Color(.32f,.36f,.38f);RenderSettings.ambientGroundColor=new Color(.18f,.2f,.18f);RenderSettings.fog=true;RenderSettings.fogMode=FogMode.ExponentialSquared;RenderSettings.fogColor=new Color(.59f,.65f,.67f);RenderSettings.fogDensity=.003f;
  var surface=ground.GetComponent<NavMeshSurface>();surface.useGeometry=NavMeshCollectGeometry.PhysicsColliders;surface.layerMask=~((1<<9)|(1<<8)|(1<<2)|(1<<5));surface.BuildNavMesh();var navPath=Root+"/Navigation/MainPrototypeNavMesh.asset";if(AssetDatabase.LoadAssetAtPath<NavMeshData>(navPath)!=null)throw new Exception("NavMesh asset exists");AssetDatabase.CreateAsset(surface.navMeshData,navPath);EditorUtility.SetDirty(surface);
  EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());EditorSceneManager.SaveScene(SceneManager.GetActiveScene());AssetDatabase.SaveAssets();
  // Main owns the persistent player; Collection receives that same instance.
  return new {scene="01_Main",shelterWidth=48,gateWidth=8,navmeshVertices=NavMesh.CalculateTriangulation().vertices.Length,playerAnimator=Object.FindFirstObjectByType<PlayerController>().visualAnimator!=null};
 }
}



