using System;using System.Linq;using System.IO;using System.Collections.Generic;using UnityEngine;using UnityEditor;using UnityEditor.Animations;using Object=UnityEngine.Object;
public static class SetupPrototypeAssets {
 public const string Root="Assets/04_Assets/PrototypeShelterV1";
 static string[] Names={"Survivor","CoreGenerator","WorkshopModule","ResearchCabin","ResidenceModule","PerimeterWall","Barricade","SupplyCrate","LightMast"};
 public static object Main(){if(EditorApplication.isPlaying)throw new Exception("Stop Play");foreach(var d in new[]{"Materials","Prefabs","Animation","Navigation"})Directory.CreateDirectory(Root+"/"+d);AssetDatabase.Refresh();
  var palette=Newtonsoft.Json.Linq.JObject.Parse(File.ReadAllText(Root+"/palette.json"));var shader=Shader.Find("Universal Render Pipeline/Lit");if(shader==null)throw new Exception("URP shader unavailable");
  var grain=Texture("SurfaceGrain",false);var paving=Texture("ConcretePaving",true);
  foreach(var pair in palette){var data=pair.Value;Color color;ColorUtility.TryParseHtmlString("#"+(string)data["hex"],out color);var path=Root+"/Materials/"+pair.Key+".mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(mat==null){mat=new Material(shader);AssetDatabase.CreateAsset(mat,path);}mat.SetColor("_BaseColor",color);mat.SetFloat("_Metallic",(float)data["metallic"]);mat.SetFloat("_Smoothness",1-(float)data["roughness"]);if(pair.Key!="Glow"&&pair.Key!="Glass"){mat.SetTexture("_BaseMap",grain);mat.SetTextureScale("_BaseMap",new Vector2(3,3));}if(pair.Key=="Glow"){mat.EnableKeyword("_EMISSION");mat.SetColor("_EmissionColor",color*1.4f);}EditorUtility.SetDirty(mat);}
  foreach(var name in Names){var path=Root+"/Models/"+name+".fbx";var imp=(ModelImporter)AssetImporter.GetAtPath(path);imp.materialImportMode=ModelImporterMaterialImportMode.ImportStandard;imp.importCameras=false;imp.importLights=false;imp.isReadable=false;foreach(var pair in palette)imp.AddRemap(new AssetImporter.SourceAssetIdentifier(typeof(Material),pair.Key),AssetDatabase.LoadAssetAtPath<Material>(Root+"/Materials/"+pair.Key+".mat"));if(name=="Survivor"){imp.animationType=ModelImporterAnimationType.Generic;imp.avatarSetup=ModelImporterAvatarSetup.CreateFromThisModel;imp.importAnimation=true;var clips=imp.defaultClipAnimations;foreach(var c in clips){c.loopTime=true;c.lockRootRotation=true;c.lockRootHeightY=true;c.lockRootPositionXZ=true;}imp.clipAnimations=clips;}else imp.importAnimation=false;imp.SaveAndReimport();}
  var controllerPath=Root+"/Animation/SurvivorLocomotion.controller";var controller=AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);if(controller==null){controller=AnimatorController.CreateAnimatorControllerAtPath(controllerPath);controller.AddParameter("MoveSpeed",AnimatorControllerParameterType.Float);var state=controller.layers[0].stateMachine.AddState("Locomotion");var tree=new BlendTree{name="Idle Walk Run",blendType=BlendTreeType.Simple1D,blendParameter="MoveSpeed",useAutomaticThresholds=false};AssetDatabase.AddObjectToAsset(tree,controller);var clips=AssetDatabase.LoadAllAssetsAtPath(Root+"/Models/Survivor.fbx").OfType<AnimationClip>().Where(c=>!c.name.StartsWith("__preview__")).ToArray();tree.AddChild(clips.Single(c=>c.name.EndsWith("Idle")),0);tree.AddChild(clips.Single(c=>c.name.EndsWith("Walk")),5);tree.AddChild(clips.Single(c=>c.name.EndsWith("Run")),10);state.motion=tree;controller.layers[0].stateMachine.defaultState=state;EditorUtility.SetDirty(controller);}
  var facts=new List<object>();foreach(var name in Names){var model=AssetDatabase.LoadAssetAtPath<GameObject>(Root+"/Models/"+name+".fbx");var go=(GameObject)PrefabUtility.InstantiatePrefab(model);go.name=name;go.transform.position=Vector3.zero;if(name!="Survivor"){var mesh=go;go=new GameObject(name);mesh.transform.SetParent(go.transform,true);}if(name=="Survivor"){var anim=go.GetComponent<Animator>()??go.AddComponent<Animator>();anim.runtimeAnimatorController=controller;anim.applyRootMotion=false;anim.cullingMode=AnimatorCullingMode.AlwaysAnimate;}var bounds=new Bounds(Vector3.zero,Vector3.zero);bool first=true;foreach(var r in go.GetComponentsInChildren<Renderer>()){if(first){bounds=r.bounds;first=false;}else bounds.Encapsulate(r.bounds);}PrefabUtility.SaveAsPrefabAsset(go,Root+"/Prefabs/"+name+".prefab");facts.Add(new{name,bounds=bounds.ToString(),renderers=go.GetComponentsInChildren<Renderer>().Length,materials=go.GetComponentsInChildren<Renderer>().SelectMany(r=>r.sharedMaterials).Select(m=>m!=null?m.name:"null").Distinct().ToArray()});Object.DestroyImmediate(go);}
  MakeFloor("Courtyard",new Color(.56f,.57f,.53f),paving,24);MakeFloor("Outside",new Color(.26f,.3f,.28f),grain,60);MakeFloor("Walkway",new Color(.37f,.4f,.38f),paving,6);AssetDatabase.SaveAssets();return facts;}
 static void MakeFloor(string name,Color color,Texture2D tex,float tiling){var path=Root+"/Materials/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(m==null){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,path);}m.color=color;m.SetTexture("_BaseMap",tex);m.SetTextureScale("_BaseMap",Vector2.one*tiling);m.SetFloat("_Smoothness",.08f);EditorUtility.SetDirty(m);}
 static Texture2D Texture(string name,bool paving){string path=Root+"/Textures/"+name+".png";if(!File.Exists(path)){int n=paving?512:256;var t=new Texture2D(n,n,TextureFormat.RGBA32,false);var pixels=new Color[n*n];var random=new System.Random(77);for(int y=0;y<n;y++)for(int x=0;x<n;x++){float noise=(float)random.NextDouble();float value=.78f+noise*.18f;if(paving){value=.79f+noise*.11f+Mathf.PerlinNoise(x*.024f,y*.024f)*.1f;if(x<3||y<3||x>n-4||y>n-4)value=.42f+noise*.08f;if(Mathf.Abs(x-(n*.3f+Mathf.Sin(y*.035f)*5))<.7f&&y>n*.7f)value*=.7f;}pixels[y*n+x]=new Color(value,value,value,1);}t.SetPixels(pixels);t.Apply();File.WriteAllBytes(path,t.EncodeToPNG());Object.DestroyImmediate(t);AssetDatabase.ImportAsset(path);}var imp=(TextureImporter)AssetImporter.GetAtPath(path);imp.wrapMode=TextureWrapMode.Repeat;imp.filterMode=FilterMode.Trilinear;imp.anisoLevel=4;imp.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Texture2D>(path);}
}

